version: '2'
services:
  quotster_db:
    image: mongo
  quotster_web:
    build: .
    working_dir: /code
    depends_on:
      - quotster_db
    expose:
      - 3000
  quotster_lb:
    image: dockercloud/haproxy
    links:
      - quotster_web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 80
